/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as CartRouteImport } from './routes/cart'
import { Route as CategoriesRouteImport } from './routes/categories'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CuisinesRouteImport } from './routes/cuisines'
import { Route as DiagnosticsRouteImport } from './routes/diagnostics'
import { Route as DrinksRouteImport } from './routes/drinks'
import { Route as FoodRouteImport } from './routes/food'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as SearchRouteImport } from './routes/search'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as CategorySlugRouteImport } from './routes/category.$slug'
import { Route as CuisineSlugRouteImport } from './routes/cuisine.$slug'
import { Route as DishSlugRouteImport } from './routes/dish.$slug'
import { Route as DishesIndexRouteImport } from './routes/dishes.index'
import { Route as DishesDishIdRouteImport } from './routes/dishes.$dishId'
import { Route as OrdersIndexRouteImport } from './routes/orders.index'
import { Route as OrdersOrderIdRouteImport } from './routes/orders.$orderId'
import { Route as VendorsIndexRouteImport } from './routes/vendors.index'
import { Route as VendorsVendorIdRouteImport } from './routes/vendors.$vendorId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const CartRoute = CartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoriesRoute = CategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CuisinesRoute = CuisinesRouteImport.update({
  id: '/cuisines',
  path: '/cuisines',
  getParentRoute: () => rootRouteImport,
} as any)
const DiagnosticsRoute = DiagnosticsRouteImport.update({
  id: '/diagnostics',
  path: '/diagnostics',
  getParentRoute: () => rootRouteImport,
} as any)
const DrinksRoute = DrinksRouteImport.update({
  id: '/drinks',
  path: '/drinks',
  getParentRoute: () => rootRouteImport,
} as any)
const FoodRoute = FoodRouteImport.update({
  id: '/food',
  path: '/food',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const CategorySlugRoute = CategorySlugRouteImport.update({
  id: '/category/$slug',
  path: '/category/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const CuisineSlugRoute = CuisineSlugRouteImport.update({
  id: '/cuisine/$slug',
  path: '/cuisine/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const DishSlugRoute = DishSlugRouteImport.update({
  id: '/dish/$slug',
  path: '/dish/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const DishesIndexRoute = DishesIndexRouteImport.update({
  id: '/dishes/',
  path: '/dishes/',
  getParentRoute: () => rootRouteImport,
} as any)
const DishesDishIdRoute = DishesDishIdRouteImport.update({
  id: '/dishes/$dishId',
  path: '/dishes/$dishId',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdersIndexRoute = OrdersIndexRouteImport.update({
  id: '/orders/',
  path: '/orders/',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdersOrderIdRoute = OrdersOrderIdRouteImport.update({
  id: '/orders/$orderId',
  path: '/orders/$orderId',
  getParentRoute: () => rootRouteImport,
} as any)
const VendorsIndexRoute = VendorsIndexRouteImport.update({
  id: '/vendors/',
  path: '/vendors/',
  getParentRoute: () => rootRouteImport,
} as any)
const VendorsVendorIdRoute = VendorsVendorIdRouteImport.update({
  id: '/vendors/$vendorId',
  path: '/vendors/$vendorId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/cart': typeof CartRoute
  '/categories': typeof CategoriesRoute
  '/contact': typeof ContactRoute
  '/cuisines': typeof CuisinesRoute
  '/diagnostics': typeof DiagnosticsRoute
  '/drinks': typeof DrinksRoute
  '/food': typeof FoodRoute
  '/privacy': typeof PrivacyRoute
  '/search': typeof SearchRoute
  '/terms': typeof TermsRoute
  '/category/$slug': typeof CategorySlugRoute
  '/cuisine/$slug': typeof CuisineSlugRoute
  '/dish/$slug': typeof DishSlugRoute
  '/dishes/$dishId': typeof DishesDishIdRoute
  '/orders/$orderId': typeof OrdersOrderIdRoute
  '/vendors/$vendorId': typeof VendorsVendorIdRoute
  '/dishes/': typeof DishesIndexRoute
  '/orders/': typeof OrdersIndexRoute
  '/vendors/': typeof VendorsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/cart': typeof CartRoute
  '/categories': typeof CategoriesRoute
  '/contact': typeof ContactRoute
  '/cuisines': typeof CuisinesRoute
  '/diagnostics': typeof DiagnosticsRoute
  '/drinks': typeof DrinksRoute
  '/food': typeof FoodRoute
  '/privacy': typeof PrivacyRoute
  '/search': typeof SearchRoute
  '/terms': typeof TermsRoute
  '/category/$slug': typeof CategorySlugRoute
  '/cuisine/$slug': typeof CuisineSlugRoute
  '/dish/$slug': typeof DishSlugRoute
  '/dishes/$dishId': typeof DishesDishIdRoute
  '/orders/$orderId': typeof OrdersOrderIdRoute
  '/vendors/$vendorId': typeof VendorsVendorIdRoute
  '/dishes': typeof DishesIndexRoute
  '/orders': typeof OrdersIndexRoute
  '/vendors': typeof VendorsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/cart': typeof CartRoute
  '/categories': typeof CategoriesRoute
  '/contact': typeof ContactRoute
  '/cuisines': typeof CuisinesRoute
  '/diagnostics': typeof DiagnosticsRoute
  '/drinks': typeof DrinksRoute
  '/food': typeof FoodRoute
  '/privacy': typeof PrivacyRoute
  '/search': typeof SearchRoute
  '/terms': typeof TermsRoute
  '/category/$slug': typeof CategorySlugRoute
  '/cuisine/$slug': typeof CuisineSlugRoute
  '/dish/$slug': typeof DishSlugRoute
  '/dishes/$dishId': typeof DishesDishIdRoute
  '/orders/$orderId': typeof OrdersOrderIdRoute
  '/vendors/$vendorId': typeof VendorsVendorIdRoute
  '/dishes/': typeof DishesIndexRoute
  '/orders/': typeof OrdersIndexRoute
  '/vendors/': typeof VendorsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/auth'
    | '/cart'
    | '/categories'
    | '/contact'
    | '/cuisines'
    | '/diagnostics'
    | '/drinks'
    | '/food'
    | '/privacy'
    | '/search'
    | '/terms'
    | '/category/$slug'
    | '/cuisine/$slug'
    | '/dish/$slug'
    | '/dishes/$dishId'
    | '/orders/$orderId'
    | '/vendors/$vendorId'
    | '/dishes/'
    | '/orders/'
    | '/vendors/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/auth'
    | '/cart'
    | '/categories'
    | '/contact'
    | '/cuisines'
    | '/diagnostics'
    | '/drinks'
    | '/food'
    | '/privacy'
    | '/search'
    | '/terms'
    | '/category/$slug'
    | '/cuisine/$slug'
    | '/dish/$slug'
    | '/dishes/$dishId'
    | '/orders/$orderId'
    | '/vendors/$vendorId'
    | '/dishes'
    | '/orders'
    | '/vendors'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/auth'
    | '/cart'
    | '/categories'
    | '/contact'
    | '/cuisines'
    | '/diagnostics'
    | '/drinks'
    | '/food'
    | '/privacy'
    | '/search'
    | '/terms'
    | '/category/$slug'
    | '/cuisine/$slug'
    | '/dish/$slug'
    | '/dishes/$dishId'
    | '/orders/$orderId'
    | '/vendors/$vendorId'
    | '/dishes/'
    | '/orders/'
    | '/vendors/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AuthRoute: typeof AuthRoute
  CartRoute: typeof CartRoute
  CategoriesRoute: typeof CategoriesRoute
  ContactRoute: typeof ContactRoute
  CuisinesRoute: typeof CuisinesRoute
  DiagnosticsRoute: typeof DiagnosticsRoute
  DrinksRoute: typeof DrinksRoute
  FoodRoute: typeof FoodRoute
  PrivacyRoute: typeof PrivacyRoute
  SearchRoute: typeof SearchRoute
  TermsRoute: typeof TermsRoute
  CategorySlugRoute: typeof CategorySlugRoute
  CuisineSlugRoute: typeof CuisineSlugRoute
  DishSlugRoute: typeof DishSlugRoute
  DishesDishIdRoute: typeof DishesDishIdRoute
  OrdersOrderIdRoute: typeof OrdersOrderIdRoute
  VendorsVendorIdRoute: typeof VendorsVendorIdRoute
  DishesIndexRoute: typeof DishesIndexRoute
  OrdersIndexRoute: typeof OrdersIndexRoute
  VendorsIndexRoute: typeof VendorsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/categories': {
      id: '/categories'
      path: '/categories'
      fullPath: '/categories'
      preLoaderRoute: typeof CategoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cuisines': {
      id: '/cuisines'
      path: '/cuisines'
      fullPath: '/cuisines'
      preLoaderRoute: typeof CuisinesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/diagnostics': {
      id: '/diagnostics'
      path: '/diagnostics'
      fullPath: '/diagnostics'
      preLoaderRoute: typeof DiagnosticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/drinks': {
      id: '/drinks'
      path: '/drinks'
      fullPath: '/drinks'
      preLoaderRoute: typeof DrinksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/food': {
      id: '/food'
      path: '/food'
      fullPath: '/food'
      preLoaderRoute: typeof FoodRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/category/$slug': {
      id: '/category/$slug'
      path: '/category/$slug'
      fullPath: '/category/$slug'
      preLoaderRoute: typeof CategorySlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cuisine/$slug': {
      id: '/cuisine/$slug'
      path: '/cuisine/$slug'
      fullPath: '/cuisine/$slug'
      preLoaderRoute: typeof CuisineSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dish/$slug': {
      id: '/dish/$slug'
      path: '/dish/$slug'
      fullPath: '/dish/$slug'
      preLoaderRoute: typeof DishSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dishes/': {
      id: '/dishes/'
      path: '/dishes'
      fullPath: '/dishes/'
      preLoaderRoute: typeof DishesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dishes/$dishId': {
      id: '/dishes/$dishId'
      path: '/dishes/$dishId'
      fullPath: '/dishes/$dishId'
      preLoaderRoute: typeof DishesDishIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orders/': {
      id: '/orders/'
      path: '/orders'
      fullPath: '/orders/'
      preLoaderRoute: typeof OrdersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orders/$orderId': {
      id: '/orders/$orderId'
      path: '/orders/$orderId'
      fullPath: '/orders/$orderId'
      preLoaderRoute: typeof OrdersOrderIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vendors/': {
      id: '/vendors/'
      path: '/vendors'
      fullPath: '/vendors/'
      preLoaderRoute: typeof VendorsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vendors/$vendorId': {
      id: '/vendors/$vendorId'
      path: '/vendors/$vendorId'
      fullPath: '/vendors/$vendorId'
      preLoaderRoute: typeof VendorsVendorIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AuthRoute: AuthRoute,
  CartRoute: CartRoute,
  CategoriesRoute: CategoriesRoute,
  ContactRoute: ContactRoute,
  CuisinesRoute: CuisinesRoute,
  DiagnosticsRoute: DiagnosticsRoute,
  DrinksRoute: DrinksRoute,
  FoodRoute: FoodRoute,
  PrivacyRoute: PrivacyRoute,
  SearchRoute: SearchRoute,
  TermsRoute: TermsRoute,
  CategorySlugRoute: CategorySlugRoute,
  CuisineSlugRoute: CuisineSlugRoute,
  DishSlugRoute: DishSlugRoute,
  DishesDishIdRoute: DishesDishIdRoute,
  OrdersOrderIdRoute: OrdersOrderIdRoute,
  VendorsVendorIdRoute: VendorsVendorIdRoute,
  DishesIndexRoute: DishesIndexRoute,
  OrdersIndexRoute: OrdersIndexRoute,
  VendorsIndexRoute: VendorsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
